os:
  - linux
services:
  - docker
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - $HOME/.gradle
env:
  global:
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
before_install:
  - jdk_switcher use oraclejdk8
  - java -version
  - sudo /etc/init.d/postgresql stop
script:
  - chmod +x gradlew
  - ./gradlew clean test
  - ./gradlew bootRepackage -x test
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false