spring:
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/master
        username: postgres
        password: 123
    jpa:
        hibernate.ddl-auto: create-drop
        database: POSTGRESQL